name: Python Flask CI/CD

on:
  push:
    branches: [main]   # Trigger only when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          echo "✅ Tests Passed!"   # Replace with actual pytest command if available

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
